development: &non_production_settings
  site_url: http://test.it
  site_name: Cambiami
  admin_email: xxxx@test.it
  redazione: "xxxx@test.it"
  noreply_email: "Cambiami <noreply@test.it>"

test:
  <<: *non_production_settings

production:
  site_url: http://www.test.it
  site_name: Cambiami
  admin_email: xxxx@test.it
  redazione: "xxxx@test.it"
  noreply_email: "Cambiami <noreply@test.it>"
